package com.bank.profile;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

import com.bank.profile.Profile;
import com.bank.profile.ProfileRepository;


@Controller    // This means that this class is a Controller
@RequestMapping(path="/profile") // This means URL's start with /profile (after Application path)
public class ProfileController {
	@Autowired // This means to get the bean called userRepository
	           // Which is auto-generated by Spring, we will use it to handle the data
	private ProfileRepository profileRepository;
	
	
	@GetMapping(path="/all")
	public @ResponseBody Iterable<Profile> getAllUsers() {
		// This returns a JSON or XML with the users
		return profileRepository.findAll();
	}
	
	@GetMapping(path="/all/{id}")
	public @ResponseBody Profile getProfile(@PathVariable Long id){
		return profileRepository.findOne(id);
	}
}
